fitnessApp/urls.py
from django.urls import path
from fitnessApp.views import *

urlpatterns = [

    path("", HomeView.as_view(), name="home"),
    path("workouts", WorkoutListView.as_view(), name="workouts"),
    path("workouts/create", WorkoutCreateView.as_view(), name="workout-create"),
    path("workouts/<int:pk>/details", WorkoutDetailView.as_view(), name="workout-detail"),

    path("exercises", ExerciseListView.as_view(), name="exercises"),
    path("exercises/create", ExerciseCreateView.as_view(), name="exercise-create"),
    path("exercises/<int:pk>/details", ExerciseDetailView.as_view(), name="exercise-detail"),

    path("workouts/<int:workout_id>/workoutsession/create", WorkoutSessionCreateView.as_view(), name="workoutsession-create"),

    path("workoutsessions/<int:pk>/run", WorkoutSessionRunView.as_view(), name="workoutsession-run"),  
    path("workoutsessions/<int:workoutsession_id>/run/<int:sequencenumber>", WorkoutSessionStepView.as_view(), name="workoutsession-step"),  

    path("builder", WorkoutSessionBuildView.as_view(), name="builder"),

    path("profile", ProfileView.as_view(), name="profile"),
    path("profile/<int:pk>/details", AccountUpdateView.as_view(), name="account-details"),  
    path("profile/coach/<int:pk>/details", CoachDetailView.as_view(), name="coach-details"),
    
    path("clients", ClientListView.as_view(), name="clients"),
    path("clients/create", ClientCreateView.as_view(), name="client-create"),
    path("clients/<int:pk>/details", ClientUpdateView.as_view(), name="client-details"),

    path("workoutsessions/<int:pk>/do", WorkoutSessionDoView.as_view(), name="workoutsession-do"),  

]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='/fitnessApp/'), name='default'),
    path('admin/', admin.site.urls),
    path("fitnessApp/", include("fitnessApp.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
]

fitnessApp/models/workoutSession_models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import AbstractUser
from fitnessApp.choices import *
from .workout_models import *
from .fitnessAppUser_models import *
from .exercise_models import *

class WorkoutSession(models.Model):
    workout = models.ForeignKey(Workout, on_delete=models.CASCADE)
    person = models.ForeignKey(FitnessAppPerson, on_delete=models.CASCADE, default="")
    scheduled_date = models.DateField(null=True, blank=True)
    scheduled_time = models.TimeField(null=True, blank=True)
    status = models.CharField(max_length=20, choices=WORKOUT_SESSION_STATUS_CHOICES, default="CREATED")
    current_step_sequence = models.IntegerField(default = 1)

class WorkoutSessionStep(models.Model):
    workoutSession = models.ForeignKey(WorkoutSession, on_delete=models.CASCADE)
    circuit = models.ForeignKey(WorkoutCircuit, on_delete=models.CASCADE)
    exercise = models.ForeignKey(Exercise, on_delete=models.CASCADE)
    circuit_exercise = models.ForeignKey(CircuitExercise, on_delete=models.CASCADE)
    set = models.IntegerField(default = 0)
    rest_after = models.IntegerField(default = 0)
    rest_before = models.IntegerField(default = 0)
    sequence_number = models.IntegerField(default = 0)
    first_flag = models.BooleanField(default=False)
    last_flag = models.BooleanField(default=False)

    class Meta:
        ordering = ['sequence_number']

fitnessApp/models/workout_models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import AbstractUser
from fitnessApp.choices import *
from .exercise_models import *

class Workout(models.Model):
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=500, blank=True)
    duration = models.IntegerField(default = 60)
    difficulty_level = models.CharField(max_length=20, choices=DIFFICULTY_LEVEL_CHOICES, default="INTERMEDIATE")
    target = models.CharField(max_length=20, choices=TARGET_CHOICES, default="WHOLEBODY")
    public_flag = models.BooleanField(default=False)
    video_id = models.CharField(max_length=50, blank=True)
    #TBD target multiple, user_id

    def get_absolute_url(self):
        return reverse("workouts")

class WorkoutCircuit(models.Model):
    workout = models.ForeignKey(Workout, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    sets = models.IntegerField(default = 2)
    set_rest = models.IntegerField(default = 120)
    exercise_rest = models.IntegerField(default = 30)

    def get_absolute_url(self):
        return reverse("circuits")
    
class CircuitExercise(models.Model):
    circuit = models.ForeignKey(WorkoutCircuit, on_delete=models.CASCADE)
    exercise = models.ForeignKey(Exercise, on_delete=models.CASCADE)
    # number of reps or number of seconds for the exercise based on the mode of the exercise
    mode =  models.CharField(max_length=20, choices=MODE_CHOICES, default="REPS")
    reps = models.IntegerField(default = 0)
    time = models.IntegerField(default = 0)
    recommended_weight = models.IntegerField(default = 0, null=True)

fitnessApp/forms.py
from django import forms
from datetime import date
from django.forms import CharField, EmailField
from django.contrib.auth.forms import UserCreationForm, UsernameField
from fitnessApp.choices import MODE_CHOICES
from fitnessApp.models import Exercise, Workout, WorkoutSession, FitnessAppUser, FitnessAppPerson

class ExerciseCreateForm(forms.ModelForm):
    class Meta:
        model = Exercise
        fields = "__all__"

class WorkoutCreateForm(forms.ModelForm):
    class Meta:
        model = Workout
        fields = "__all__"

class ClientCreateForm(forms.ModelForm):

    class Meta:
        model = FitnessAppPerson
        fields = ("first_name", "last_name", "coach", "phone_number", "email",)

class WorkoutSessionCreateForm(forms.ModelForm):
    class Meta:
        model = WorkoutSession
        fields = ["scheduled_date"]
        widgets = {
            'scheduled_date': forms.DateInput(attrs={'type': 'date', 'min': str(date.today())}, ),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['scheduled_date'].required = False

class FitnessAppUserUpdateForm(forms.ModelForm):

    class Meta:
        model = FitnessAppUser
        fields = ("first_name", "last_name")
        field_classes = {"first_name": CharField, "last_name": CharField}
        labels = {"first_name": "First Name", "last_name": "Last Name"}

class FitnessAppPersonUpdateForm(forms.ModelForm):
    class Meta:
        model = FitnessAppPerson
        fields = ("first_name", "last_name", "phone_number", "email")
        field_classes = {"first_name": CharField, "last_name": CharField}
        labels = {"first_name": "First Name", "last_name": "Last Name"}

SETS = [
    ('1', '1'),
    ('2', '2'),
    ('3', '3'),
    ('4', '4'),
    ('5', '5'),
]

CIRCUITS = [
    ('1', '1'),
    ('2', '2'),
    ('3', '3'),
    ('4', '4'),
    ('5', '5'),
]

class WorkoutSessionBuildForm(forms.Form):

    session_client = forms.ChoiceField()
    session_date = forms.DateField()
    session_time = forms.TimeField()

    number_of_circuits = forms.ChoiceField(choices=CIRCUITS,  widget=forms.RadioSelect(), initial=1)
    circuit_sets = forms.ChoiceField(choices=SETS,  widget=forms.RadioSelect(), initial=3)

    set_rest = forms.IntegerField()
    exercise_rest = forms.IntegerField()

    exercise_mode = forms.ChoiceField(choices=MODE_CHOICES,  widget=forms.RadioSelect(), initial=1)
    exercise_reps = forms.IntegerField()
    exercise_time = forms.IntegerField()

    exercises_1 = forms.CharField(required = False)
    exercises_2 = forms.CharField(required = False)
    exercises_3 = forms.CharField(required = False)
    exercises_4 = forms.CharField(required = False)
    exercises_5 = forms.CharField(required = False)

    def __init__(self, *args, **kwargs):
        
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

        for circuitIndex in range (0, 5):
            for exerciseIndex in range (0, 15):
                self.fields[f'exercise_quantity_{circuitIndex + 1}_{exerciseIndex + 1}'] = forms.IntegerField()
                self.fields[f'exercise_mode_{circuitIndex + 1}_{exerciseIndex + 1}'] = forms.ChoiceField(choices=MODE_CHOICES,  widget=forms.RadioSelect(), initial=1)

        clients = FitnessAppPerson.objects.filter(coach=user.person).order_by('first_name')
        self.fields['session_client'].choices = [("", "Select a client...")] + [(client.id, (client.first_name + " " + client.last_name)) for client in clients]

fitnessApp/views.py
from django.shortcuts import get_object_or_404, render
from django.views.generic import CreateView, DeleteView, ListView, TemplateView, DetailView, View
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q, F
from datetime import date
from fitnessApp.models import *
from fitnessApp.forms import *

# Create your views here.

class HomeView(TemplateView):
    template_name = "home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        context['activeSessions'] = WorkoutSession.objects.filter(user=self.request.user, scheduled_date=date.today())
        context['upcomingSessions'] = WorkoutSession.objects.filter(Q(user=self.request.user) & (Q(scheduled_date__gt=date.today()) | Q(scheduled_date__isnull=True))).order_by((F('scheduled_date').asc(nulls_last=True)))
        context['pastSessions'] = WorkoutSession.objects.filter(user=self.request.user, scheduled_date__lt=date.today()).order_by('-scheduled_date')

        return context
    
class ExerciseListView(ListView):
    model = Exercise
    template_name = "exercise_list.html"
    paginate_by = 10

class ExerciseCreateView(LoginRequiredMixin, CreateView):
    model = Exercise
    template_name = "exercise_create.html"
    form_class = ExerciseCreateForm

class ExerciseDetailView(LoginRequiredMixin, DetailView):
    model = Exercise
    template_name = "exercise_detail.html"

class WorkoutListView(ListView):
    model = Workout
    template_name = "workout_list.html"
    paginate_by = 10

class WorkoutCreateView(LoginRequiredMixin, CreateView):
    model = Workout
    template_name = "workout_create.html"
    form_class = WorkoutCreateForm

class WorkoutDetailView(LoginRequiredMixin, DetailView):
    model = Workout
    template_name = "workout_detail.html"

class WorkoutSessionCreateView(LoginRequiredMixin, CreateView):
    model = WorkoutSession
    template_name = "workoutsession_create.html"
    form_class = WorkoutSessionCreateForm
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        workout_id = self.kwargs['workout_id']
        workout = Workout.objects.get(pk=workout_id)

        form.instance.workout = workout
        form.instance.user = self.request.user

        response = super().form_valid(form)

        seq = 1
        before = 10

        for circuit in workout.workoutcircuit_set.all():
            for setnumber in range(1, circuit.sets + 1):

                circuitexercises = circuit.circuitexercise_set.all()
                lastelement = circuitexercises.last()
                firstelement = circuitexercises.first()
                
                for circuitexercise in circuitexercises:

                    after = circuit.set_rest if circuitexercise == lastelement else circuit.exercise_rest

                    WorkoutSessionStep.objects.create(
                        workoutSession = self.object,
                        circuit = circuit,
                        exercise = circuitexercise.exercise,
                        set = setnumber,
                        rest_after = after,
                        rest_before = before,
                        sequence_number = seq,
                        first_flag = (circuitexercise == firstelement),
                        last_flag = (circuitexercise == lastelement),
                    )

                    seq += 1
                    before = after

        return response

class WorkoutSessionRunView(LoginRequiredMixin, DetailView):
    model = WorkoutSession
    template_name = "workoutsession_run.html"

class WorkoutSessionStepView(LoginRequiredMixin, DetailView):
    model = WorkoutSessionStep
    template_name = "workoutsession_step.html"

    def get_object(self, queryset=None):
        if queryset is None:
            queryset = self.get_queryset()
        
        # Custom lookup logic, e.g., using a different field
        workoutsession_id = self.kwargs.get('workoutsession_id')
        sequencenumber = self.kwargs.get('sequencenumber')
        obj = get_object_or_404(queryset, workoutSession=workoutsession_id, sequence_number=sequencenumber)
        return obj

class ProfileView(View):
    def get(self, request):
        return render(request, 'profile.html')

    

fitnessApp/views/client_views.py
from django.views.generic import CreateView, ListView, DetailView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from fitnessApp.models import *
from fitnessApp.forms import *

class ClientListView(LoginRequiredMixin, ListView):
    model = FitnessAppPerson
    template_name = "client_list.html"
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(coach=self.request.user.person)
        return queryset
    

class ClientCreateView(LoginRequiredMixin, CreateView):
    model = FitnessAppPerson
    template_name = "client_create.html"
    form_class = ClientCreateForm
    

class ClientUpdateView(LoginRequiredMixin, UpdateView):
    model = FitnessAppPerson
    form_class = FitnessAppPersonUpdateForm
    success_url = reverse_lazy("clients")
    template_name = "client_details.html"

fitnessApp/views/exercise_views.py
from django.views.generic import CreateView, ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from fitnessApp.models import *
from fitnessApp.forms import *

class ExerciseListView(ListView):
    model = Exercise
    template_name = "exercise_list.html"
    paginate_by = 10

class ExerciseCreateView(LoginRequiredMixin, CreateView):
    model = Exercise
    template_name = "exercise_create.html"
    form_class = ExerciseCreateForm

class ExerciseDetailView(LoginRequiredMixin, DetailView):
    model = Exercise
    template_name = "exercise_detail.html"

fitnessApp/views/home_views.py
from django.views.generic import TemplateView
from django.db.models import Q, F
from datetime import date
from fitnessApp.models import *
from fitnessApp.forms import *

class HomeView(TemplateView):
    template_name = "home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        if (self.request.user.is_authenticated):
            context['today'] = date.today()
            if (self.request.user.person.coach_flag):
                context['activeSessions'] = WorkoutSession.objects.filter(Q(person=self.request.user.person) | Q(person__coach=self.request.user.person), scheduled_date=date.today())
                context['upcomingSessions'] = WorkoutSession.objects.filter((Q(person=self.request.user.person) | Q(person__coach=self.request.user.person)) & (Q(scheduled_date__gt=date.today()) | Q(scheduled_date__isnull=True))).order_by((F('scheduled_date').asc(nulls_last=True)))
                context['pastSessions'] = WorkoutSession.objects.filter((Q(person=self.request.user.person) | Q(person__coach=self.request.user.person)), scheduled_date__lt=date.today()).order_by('-scheduled_date')

            else: 
                context['activeSessions'] = WorkoutSession.objects.filter(person=self.request.user.person, scheduled_date=date.today())
                context['upcomingSessions'] = WorkoutSession.objects.filter(Q(person=self.request.user.person) & (Q(scheduled_date__gt=date.today()) | Q(scheduled_date__isnull=True))).order_by((F('scheduled_date').asc(nulls_last=True)))
                context['pastSessions'] = WorkoutSession.objects.filter(person=self.request.user.person, scheduled_date__lt=date.today()).order_by('-scheduled_date')

        return context

fitnessApp/views/profile_views.py
from django.shortcuts import render
from django.views.generic import View, UpdateView, DetailView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from fitnessApp.models import *
from fitnessApp.forms import *

class ProfileView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, 'profile.html')

class AccountUpdateView(LoginRequiredMixin, UpdateView):
    model = FitnessAppUser
    form_class = FitnessAppUserUpdateForm
    success_url = reverse_lazy("profile")
    template_name = "account_details.html"

class CoachDetailView(LoginRequiredMixin, DetailView):
    model = FitnessAppPerson
    template_name = "coach_detail.html"

fitnessApp/views/workout_views.py
from django.views.generic import CreateView, ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from fitnessApp.models import *
from fitnessApp.forms import *

class WorkoutListView(ListView):
    model = Workout
    template_name = "workout_list.html"
    paginate_by = 10

class WorkoutCreateView(LoginRequiredMixin, CreateView):
    model = Workout
    template_name = "workout_create.html"
    form_class = WorkoutCreateForm

class WorkoutDetailView(LoginRequiredMixin, DetailView):
    model = Workout
    template_name = "workout_detail.html"

fitnessApp/templates/client_create.html
{% extends "base/base.html" %}
{% load crispy_forms_tags %}

{% block title %}Create Client{% endblock %}

{% block content %}

<form action="" method="post">{% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-success" type="submit">Save</button>
</form>

{% endblock %}

fitnessApp/templates/client_details.html
{% extends "base/base.html" %}
{% load crispy_forms_tags %}

{% block title %}Client Details{% endblock %}

{% block content %}

<div>
<form method="POST">{% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-success" type="submit">Save</button>
</form>
</div>

{% endblock %}

fitnessApp/templates/client_list.html
{% extends "base/base.html" %}

{% block title %}Clients{% endblock %}

{% block content %}
<div>
<div class="client-create-outer">
    <div class="client-create-inner mb-3">
        <a class="fitnessapp-profile-item" href="{% url 'client-create' %}">
            <!-- <button class="btn btn-primary" type="button">Create Client</button> -->
             <i class="bi bi-plus-circle"></i><span><small>&nbsp;Add Client</small></span>
        </a>
    </div>
</div>

<div>
    {% for item in object_list %}
   
        <ul class="list-group">
             
            <li class="list-group-item client-detail-item">
                <a class="fitnessapp-profile-item" href="{% url 'client-details' item.id %}">
                    <div class="client-detail-outer">
                        <div class="client-detail-name">
                            <h5 class="text single-line"><b>{{ item.first_name }} {{ item.last_name }}</b></h5>
                        </div>
                        <div class="client-detail-phone-number">
                            <h6 class="text single-line">{{ item.phone_number }}</h6>
                        </div>
                        <div class="client-detail-edit">
                            <i class="bi bi-chevron-right"></i>
                        </div>
                    </div>
                </a> 
            </li> 
            
        </ul>  
        
    {% empty %}
    No clients yet.
    {% endfor %}
    
</div>  
</div>


{% endblock %}

fitnessApp/templates/coach_detail.html
{% extends "base/base.html" %}

{% block title %}My Trainer{% endblock %}

{% block content %}
    <div>
        <ul class="list-group">
            <li class="list-group-item">
                <div class="workout-detail-attribute">
                    <div class="workout-detail-attribute-label"><span><b>First Name</b></span></div>
                    <div class="workout-detail-attribute-value">{{ object.first_name }}</div>
                </div>
                </li>
            <li class="list-group-item">
                <div class="workout-detail-attribute">
                    <div class="workout-detail-attribute-label"><span><b>Last Name</b></span></div>
                    <div class="workout-detail-attribute-value">{{ object.last_name }}</div>
                </div>
            </li>
            <li class="list-group-item">
                <div class="workout-detail-attribute">
                    <div class="workout-detail-attribute-label"><span><b>Email</b></span></div>
                    <div class="workout-detail-attribute-value">{{ object.person.email }}</div>
                </div>
            </li>
        </ul>
    </div>
{% endblock %}

fitnessApp/templates/exercise_create.html
{% extends "base/base.html" %}
{% load crispy_forms_tags %}

{% block title %}Create Exercise{% endblock %}

{% block content %}

<form action="" method="post">{% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Save">
</form>

{% endblock %}

fitnessApp/templates/exercise_detail.html
{% extends "base/base.html" %}

{% block title %}Details: {{ object.name }}{% endblock %}

{% block content %}

<div>
        {% include 'exercise_video.html' with video_id=object.video_id %}
        <p><b><h6>Exercise Name: </b><small>{{ object.name }}</small></h6></p>
        <p><b><h6>Description: </b><small>{{ object.description }}</small></h6></p>

{% endblock %}

fitnessApp/templates/workout_create.html
{% extends "base/base.html" %}
{% load crispy_forms_tags %}

{% block title %}Create Workout{% endblock %}

{% block content %}

<form action="" method="post">{% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Save">
</form>

{% endblock %}

fitnessApp/templates/workout_detail.html
{% extends "base/base.html" %}

{% block title %}{{ object.name }}{% endblock %}

{% block content %}
    <div>
        {% include 'workout_detail_card.html' with workoutObject=object %}
    </div>
{% endblock %}

fitnessApp/templates/workout_detail_card.html
        <ul class="list-group">
            <li class="list-group-item">
                <div class="workout-detail-attribute">
                    <div class="workout-detail-attribute-label"><span><b>Duration</b></span></div>
                    <div class="workout-detail-attribute-valuee">{{workoutObject.duration}} minutes</div>
                </div>
                </li>
            <li class="list-group-item">
                <div class="workout-detail-attribute">
                    <div class="workout-detail-attribute-label"><span><b>Difficulty</b></span></div>
                    <div class="workout-detail-attribute-valuee">{{workoutObject.get_difficulty_level_display}}</div>
                </div>
            </li>
            <li class="list-group-item">
                <div class="workout-detail-attribute">
                    <div class="workout-detail-attribute-label"><span><b>Target</b></span></div>
                    <div class="workout-detail-attribute-valuee">{{workoutObject.get_target_display}}</div>
                </div>
            </li>
        </ul>
        </br>
        {% for workoutcircuit in workoutObject.workoutcircuit_set.all %}
            <div class="workout-circuit-heading"><small><b>{{ workoutcircuit.name }} &nbsp;&nbsp;&nbsp;</b>{{ workoutcircuit.sets }} sets</small></div>
                    {% for circuitexercise in workoutcircuit.circuitexercise_set.all %}
                        {% include 'exercise_card.html' with item=circuitexercise.exercise %}
                    {% endfor %}
        {% endfor %}

fitnessApp/templates/workoutsession_step.html
{% extends "base/base_no_footer.html" %}
{% load static %}

{% block scripts %}
{{ block.super }}
<script>
  var totalSeconds = "{{ object.rest_before }}";
  var check = "{{ object.circuitexercise.mode }}";
  var exerciseTime = "{{ object.circuit_exercise.time }}";
  var modeQuantity = "{{ object.circuit_exercise.reps }}";
  var current_initial = "{{ object.workoutSession.current_step_sequence }}";
  var current_final = "{{ object.workoutSession.workoutsessionstep_set.all|length }}";
</script>
<script src="{% static 'js/workoutSessionRun.js' %}"></script>
{% endblock %}

{% block title %}Workout: {{ object.workoutSession.workout.name }}{% endblock %}

{% block content %}
<div class="workout-session-run-outer">

  <div class="workout-session-run-row-video">
    <div class="workout-session-progress-bar-video-exercise-outer">
      <div class="workout-session-topblock">
        <div class="workout-session-topblock-circuit-set">
          <span class="badge rounded-pill text-bg-light" style="margin-right: 0.2rem;">{{object.circuit.name}}</span><span class="badge rounded-pill text-bg-light">Set {{object.set}}</span>
        </div>
        <div class="workout-session-progress-bar">
          <div class="fitnessapp-progress-container">
            <div class="fitnessapp-progress-bar" id="progressBar">
            </div>
          </div>
        </div>
      </div>
    
      <div class="workout-session-video">
        {% include 'exercise_video.html' with video_id=object.exercise.video_id name=object.exercise.name %}
      </div>

      <div class="workout-session-exercise">

        <div class="workout-session-exercise-circuit-set-outer">
            <h5>{{object.exercise.name}}</h5>
        </div>

      </div>
    </div>
  </div>

  <div class="workout-session-run-row-controls">
    <div class="workout-session-rest-reps-outer">
      <div class="workout-session-rest-display">
        <span>Rest <b>{{ object.rest_before }}</b> seconds</span>
      </div>
      <div class="workout-session-reps-display">
          {% if object.circuit_exercise.mode == "TIME" %}
            <b>{{ object.circuit_exercise.time }}</b> seconds
          {% else %}
            <b>{{ object.circuit_exercise.reps }}</b> reps
          {% endif %}
      </div>
    </div>

    <div class="workout-session-controls-grid">
      <div class="workout-session-previous-button">
        <form method="GET" action="{% url 'workoutsession-step'  workoutsession_id=object.workoutSession_id sequencenumber=object.sequence_number|add:-1 %}">
            <button class="btn btn-outline-dark btn-lg" {% if object.sequence_number == 1 %}disabled{% endif %} type="submit">
              <i class="bi bi-caret-left-fill"></i>
            </button>
        </form>
      </div>

     
      <div class="workout-session-pause-resume-button">
        <form onsubmit="return false;">
          <button id="pause-button" class="btn btn-outline-dark btn-lg">
            <i id="pause-resume-button" class="bi bi-pause-circle"></i>
          </button>
        </form>
      </div>


      <div class="workout-session-next-button">
        <form id="next-form" method="GET" action="{% url 'workoutsession-step'  workoutsession_id=object.workoutSession_id sequencenumber=object.sequence_number|add:1 %}">
            <button class="btn btn-outline-dark btn-lg" {% if object.sequence_number == object.workoutSession.workoutsessionstep_set.all|length %}disabled{% endif %} type="submit">
              <i class="bi bi-caret-right-fill"></i>
            </button>
        </form>
      </div>

    </div>

    <div class="message-div-outer">
      <div id="rest-message" class="message-rest-grid-inner">
        <span class="message-text">REST UP AND GET READY!</span>
      </div>
      <div id="exercise-message" class="message-exercise-grid-inner">
        <span span class="message-text">LETS GO! HIT IT!</span>
      </div>
    </div>


    <div id="timer" class="timer-grid">
      <div class="timer-grid-inner">
        <svg preserveAspectRatio="xMidYMid meet" height="stretch" viewBox="0 0 100 100">
          <circle class="circle-bg" cx="50" cy="50" r="45" />
          <circle class="circle-progress" cx="50" cy="50" r="45" />
        </svg>
        <div class="time-text" id="time-text">--:--</div>
      </div>
    
      <div id="restart-timer-div" class="restart-timer">
        <button onclick="restartTimer()" id="restart-timer-button" class="btn btn-outline-dark btn-lg timer-button">
          <i class="bi bi-arrow-counterclockwise"></i>
          <span class="menu_label text-muted"><small><small><small>RESTART</small></small></small></span>
        </button>
      </div>
    
      <div id="skip-rest-timer-div" class="skip-rest-timer">
        <button onclick="skipTimer()" id="skip-rest-timer-button" class="btn btn-outline-dark btn-lg timer-button">
          <i class="bi bi-skip-end"></i>
          <span class="menu_label text-muted"><small><small><small>SKIP</small></small></small></span>
        </button>
      </div>
    </div>

  </div>

</div>
{% endblock %}